### ISSUE TITLE
META: rotation

### ISSUE THREAD

**Issue by stopfstedt** [ThronesDB/thronesdb#350]
braindump:
- _a card is a card is a card_ - codes will _not_ change for re-distributed cards. in other words, if for example `Hot Pie` is rotated out, and then comes back in a new pack after rotation, it will come back under its previously assigned card code `04057`. **is this assumption realistic?** or will each reprint be tracked and treated as distinct from its previous version?
- expand the card-to-pack relationship from many-to-one to many-to-many. move the pack position attribute into that relationship/join table. from a db schema perspective, this will be  the most drastic change. **may not be necessary if reprints will be treated as distinct from their previous versions**
- add a `rotated` flag to the pack entity, or perhaps even a level further up at the cycle. 
- card legality for deck building/deck publishing: in addition to existing deck building restrictions, prohibit publishing of decks that contain any cards that are _only_ linked to rotated packs.
- card details view: augment the UI to link a card to all of it's associated packs (perhaps a dropdown toggle on the pack name in the navigation, and/or a list of links to packs below the card details.)
- browsing cards in the context of packs: needs new route to provide that context of the pack under which the given card is currently viewed. e.g.  `/set/<pack-code>/card/<card-code>`, in addition to existing `/card/<card-code>` route.
- deck builder: pack filter should exclude rotated packs by default.
- new deck wizard: only include agendas that are are associated with at least one unrotated pack.
- API: card label will need to be expanded from a scalar value to a list of all possible `<card-title>  (<pack-code>)` combinations **or not, see bolded comments above**
- deck/deck-list export/download - in case an included card has been distributed in multiple packs, indicate the first un-rotated pack code in parenthesis next to the card's title, if possible

prototype this before the winter.

**Comment by stopfstedt** [comment]
has ramifications for the cards data repo(s) as well. 

@ystros any thoughts on this?

**Comment by ystros** [comment]
@stopfstedt Thanks for involving me. Let me think about it a bit and I'll try to get back to you this weekend.

**Comment by stopfstedt** [comment]
just to throw out a few more alternatives to this: 
1. _one card, multiple card codes._ first impression - eh, meh.
2. _reprints have new card code designations_. that's how cgdb and netrunnerdb are handling it, so we know it's a workable model. i dislike the idea of creating duplicate entries for what are essentially the same cards, but may be the easiest to implement.
3. _move the card code out of the card record, and into the card-to-pack relationship, along with the pack position (as mentioned earlier)._ that's more of an addendum to the idea expressed in the original post above.

**Comment by ystros** [comment]
I think there are two subjects here - rotation, and then reprinting previously rotated card (e.g. a revised Core Set).

Adding `rotated` to either pack or cycle should be sufficient for the first portion. I believe FFG does rotation by cycle, so it might be more appropriate as a data point there, but there's not much difference between that and marking individual packs as rotated.

Regarding reprints / a revised Core, it may be worth paying attention to how that worked with Netrunner. My understanding is that the revised Core re-numbered things. So in that sense, maybe there should be a new card code for reprints? 

(New card codes for existing cards is massively inconvenient from a Throneteki perspective, so I'm not a fan of it. But it might be the most consistent thing to do)

Regardless of whether we assign additional card codes or not, there does need to be a many-to-many relationship between cards and packs they appear in. Card codes could live on that relationship table (though then it's a question of what you use as a unique ID on card itself). Or just position within the pack, to denote the numbering within that pack.

In terms of how the JSON data repo could handle this, it'll have to be some sort of way of referencing other card codes. I could see it working something like:
```json
{
    "cgdbId": 54,
    "code": "Core",
    "name": "Revised Core Set",
    "releaseDate": null,
    "cards": [
        {
            "ref": "01001"
        },
        {
            "ref": "04080"
        },
        ...
    ]
}
```

Or with new card codes:
```json
{
    "cgdbId": 54,
    "code": "Core",
    "name": "Revised Core Set",
    "releaseDate": null,
    "cards": [
        {
            "code":, "17001"
            "ref": "01001"
        },
        {
            "code": "17002",
            "ref": "04080"
        },
        ...
    ]
}
```

(It's also possible that there will be no rotation, since a new cycle hasn't been announced yet)

**Comment by stopfstedt** [comment]
@ystros thanks for the input. agreed, those are separate but related issues.

been digging a little further into netrunner's revised core, and discovered yet another snag - reprints with different artwork. 

see chaos theory and gabriel santiago for examples:

https://netrunnerdb.com/en/card/01017
https://netrunnerdb.com/en/card/25020

https://netrunnerdb.com/en/card/02046
https://netrunnerdb.com/en/card/25040

so illustrator would be another data point that would have to move into the join table, and we'd definitely have to carry new card designations for reprints somehow (otherwise we won't be able to pull the correct image). mapping/aliasing old-to-new card codes as described above would work.

**Comment by stopfstedt** [comment]
this issue is off the table for now. if/when the player committee gets around to considering rotation we'll deal with this.

**Comment by ystros** [comment]
Agreed. I suspect the larger issue going forward will be whether people are interested in distinguishing between "FFG era validity" and "Player committee era validity", in which rotation may or may not factor in.
