### ISSUE TITLE
Hide banned cards in deckbuilder

### ISSUE THREAD

**Issue by mrdavnor** [ThronesDB/thronesdb#478]
Hi, it would be great if you could toggle banned cards on and off with the options menu.

**Comment by stopfstedt** [comment]
hey @mrdavnor, thanks for your suggestion. 

to expand on this a little bit - we'd need two toggles - for melee and for joust - since the banned lists for each format have diverged now from each other. 

i'll take a stab at it this month.

**Comment by stopfstedt** [comment]
Hey, so I checked into this, and while doable it's not as straightforward to do as the existing filters. Since banned list (or restricted list) membership is not a card attribute that can be filtered against in the data store, this would have to be layered on top of things. 
I'll pass on this feature request for now, but will keep this ticket open as a reminder to revisit at a later point (e.g. if/when the deckbuilder interface will be revamped).

**Comment by stopfstedt** [comment]
With the redesigns rearing their head, this is becoming a more pressing issue. Will have another stab at it this week.
